sudo: required
services
  - docker
language: python
python:
  - 3.8
script:
  - python -m pytest -v
  - flake8
after_success:
  - sh .travis/deploy_dockerhub.
  – test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh